apiVersion: v1
kind: ServiceAccount
metadata:
  name: ynab-companion-sa
  labels:
    app.kubernetes.io/name: ynab-companion
    app.kubernetes.io/part-of: ynab-companion-app
  annotations:
    # Binds this Kubernetes Service Account to a GCP IAM Service Account
    # via GKE Workload Identity.
    # Replace with your IAM Service Account email:
    iam.gke.io/gcp-service-account: "ynab-companion-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com"
